### Register a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test4@test.com",
  "password": "test"
}

### SignIn
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test3@test.com",
  "password": "test"
}

### Get currently signed in user (WhoAmI)
GET http://localhost:3000/auth/whoami

### SignOut
POST http://localhost:3000/auth/signout

### Get a user by id
GET http://localhost:3000/auth/1

### Get the users by email
GET http://localhost:3000/auth?email=test1@test.com

### Delete a user by id
DELETE http://localhost:3000/auth/2

### Update a user by id
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "alex@test.com",
  "password": "test"
}